# Generated by Django 4.1.7 on 2023-04-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='correo',
            new_name='email',
        ),
    ]
