# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicio_options_alter_servicio_contenido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicio',
            new_name='servicios',
        ),
    ]
